#!/usr/bin/env bash

## Set function
insert_comma () {
	awk '{ printf "%\047d\n", $1 }'
}

## Get Fail2Ban counts
F2B="$(ufw status | grep Fail2Ban | awk '{ print $3 }')"
F2B_COUNT="$(grep -cve '^\s*$' <<< "${F2B}")"
F2B_IP_COUNT="$(grep -v '/' <<< "${F2B}" | grep -cve '^\s*$')"
F2B_IP_COUNT_TH="$(echo ${F2B_IP_COUNT} | insert_comma)"
F2B_CIDR_COUNT="$(( F2B_COUNT - F2B_IP_COUNT ))"
F2B_CIDR_COUNT_TH="$(echo ${F2B_CIDR_COUNT} | insert_comma)"

## Get Helix Hall Of Fame counts
HHOF="$(ufw status | grep HHoF | awk '{ print $3 }')"
HHOF_COUNT="$(grep -cve '^\s*$' <<< "${HHOF}")"
HHOF_IP_COUNT="$(grep -v '/' <<< ${HHOF} | grep -cve '^\s*$')"
HHOF_IP_COUNT_TH="$(echo ${HHOF_IP_COUNT} | insert_comma)"
HHOF_CIDR_COUNT="$(( HHOF_COUNT - HHOF_IP_COUNT ))"
HHOF_CIDR_COUNT_TH="$(echo ${HHOF_CIDR_COUNT} | insert_comma)"

## Get Whitelist counts
WHTLST="$(showwhitelist | grep -vE '^\s*$|^\s*#|127\.')"
WHTLST_COUNT="$(grep -cve '^\s*$' <<< "${WHTLST}")"
WHTLST_IP_COUNT="$(grep -v '/' <<< "${WHTLST}" | grep -cve '^\s*$')"
WHTLST_IP_COUNT_TH="$(echo "${WHTLST_IP_COUNT}" | insert_comma)"
WHTLST_CIDR_COUNT="$(( WHTLST_COUNT - WHTLST_IP_COUNT ))"
WHTLST_CIDR_COUNT_TH="$(echo ${WHTLST_CIDR_COUNT} | insert_comma)"

## Set colors
GREEN="\e[1;32m"
RED="\e[1;31m"
UNDIM="\e[0m"

## Display
echo "currently banned:"
printf "${UNDIM}%-20s${RED}%-10s ${UNDIM}%-20s${RED}%-10s\n${UNDIM}" \
	"  Fail2Ban IPs......:" " ${F2B_IP_COUNT_TH}" \
	"Fail2Ban CIDR......:" " ${F2B_CIDR_COUNT_TH}"

printf "${UNDIM}%-20s${RED}%-10s ${UNDIM}%-20s${RED}%-10s\n${UNDIM}" \
	"  Hall of Fame IPs..:" " ${HHOF_IP_COUNT_TH}" \
	"Hall of Fame CIDR..:" " ${HHOF_CIDR_COUNT_TH}"

echo; echo "currently whitelisted:"
printf "${UNDIM}%-20s${GREEN}%-10s ${UNDIM}%-20s${GREEN}%-10s\n${UNDIM}" \
	"  Whitelisted IPs...:" " ${WHTLST_IP_COUNT_TH}" \
	"Whitelisted CIDR...:" " ${WHTLST_CIDR_COUNT_TH}"
