#!/bin/env bash

printf "Welcome to %s %s %s %s %s %s\n" \
	"$(uname -a | awk {'print $14'})" \
	"$(uname -o)" \
	"$(uname -r)" \
	"$(
		cat /proc/cpuinfo \
		| grep "model name" \
		| uniq \
		| cut -f 2 \
		| cut -b3-
	)" \
	"$(uname -m)"
