#!/bin/env bash

## Config
MaxUsage=90
BarWidth=50
export TERM=xterm-256color
ClrWht="\e[39m"
ClrGrn=$(tput setaf 46)
ClrRed=$(tput setaf 196)
ClrDim="\e[2m"
ClrOff="\e[0m"

## Disk usage: Ignore ZFS, SquashFS & TmpFS
mapfile -t DFS < <(
	df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay \
		--output=target,pcent,size \
	| sed '/\/tmp\//d' \
	| tail -n+2
)
printf "\ndisk usage:\n"

for Line in "${DFS[@]}"; do
	## Get disk usage
	Usage=$(echo "$Line" | awk '{ print $2 }' | sed 's/%//')
	UsedWidth=$((( $Usage * $BarWidth )/100))

	## Color is green if usage < max usage, else red
	if [[ $Usage -ge $MaxUsage ]]; then
		Color=$ClrRed
	else
		Color=$ClrGrn
	fi

	## Print green/red bar until used width
	Bar="[${Color}"
	for (( i=0; i<$UsedWidth; i++ )); do
		Bar+="="
	done

	## Print dimmmed bar until end
	Bar+="${ClrWht}${ClrDim}"
	for (( i=$UsedWidth; i<$BarWidth; i++ )); do
		Bar+="="
	done
	Bar+="${ClrOff}]"

	## Print usage line & bar
	echo "${Line}" \
	| awk '{ printf("%-31s%+3s used out of %+4s\n", $1, $2, $3); }' \
	| sed -e 's/^/  /'
	echo -e "${Bar}" \
	| sed -e 's/^/  /'
done
