#!/bin/env bash

## Set variables
Columns=2
export TERM=xterm-256color
ClrGrn=$(tput setaf 46)
ClrRed=$(tput setaf 196)
ClrOff=$(tput sgr0)
Servers=(
	"bingo"
	"currencyexchange"
	"34swap"
	"chatcord"
)

## Sort display
IFS=$'\n' read -r Servers <<< "$(sort <<<"${Servers[*]}")"
unset IFS

## Get status of all node.js servers
Status=()
for Server in "${Servers[@]}"; do
	if pgrep -f "$Server" > /dev/null; then
		Status+=( "active" )
	else
		Status+=( "inactive" )
	fi
done

Out=
for i in "${!Servers[@]}"; do
	if [[ "${Status[$i]}" == "active" ]]; then
		Clr=$ClrGrn
	else
		Clr=$ClrRed
	fi
	Out+="${Servers[$i]}:,${Clr}${Status[$i]}${ClrOff},"

	## Insert newline every column
	if [ $(((i+1) % Columns)) -eq 0 ]; then
		Out+="\n"
	fi
done

## Print things on the screen
printf "\nNode.js Servers:\n"
printf "%s\n" "$Out" | column -ts $',' | sed -e 's/^/  /'
