#!/bin/env bash

## Set variables
COLUMNS=2
export TERM=xterm-256color
GREEN=$(tput setaf 46)
RED=$(tput setaf 196)
UNDIM="\e[0m"
SERVERS=(
	"bingo"
	"currencyexchange"
	"34swap"
	"chatcord"
)

## Sort display
IFS=$'\n' SERVERS=($(sort <<<"${SERVERS[*]}"))
unset IFS

## Get status of all node.js servers
STATUS=()
for SERVER in "${SERVERS[@]}"; do
	if [[ $(pgrep -f "${SERVER}") ]]; then
		STATUS+=( "active" )
	else
		STATUS+=( "inactive" )
	fi
done

OUT=""
for i in "${!SERVERS[@]}"; do
	if [[ "${STATUS[$i]}" == "active" ]]; then
		OUT+="${SERVERS[$i]}:,${GREEN}${STATUS[$i]}${UNDIM},"
	else
		OUT+="${SERVERS[$i]}:,${RED}${STATUS[$i]}${UNDIM},"
	fi

	## Insert newline every column
	if [ $(((i+1) % COLUMNS)) -eq 0 ]; then
		OUT+="\n"
	fi
done

## Print things on the screen
echo; echo "Node.js Servers:"
echo -e "${OUT}" | column -ts $',' | sed -e 's/^/  /'
