#!/usr/bin/env bash

## Get Fail2Ban counts
Fail2BanIPs=$(
	/sbin/route -n \
	| grep '\*' \
	| awk '{ print $1,$4,$5 }' \
	| grep -v " 0" \
	| grep -v ".0 "
)
Fail2banIPCount=$(
	grep -v '/' <<< "$Fail2BanIPs" | grep -cve '^\s*$'
)
Fail2BanCIDR=$(
	/sbin/route -n \
	| grep '\*' \
	| awk '{ print $1,$4,$5 }' \
	| grep -v " 0" \
	| grep ".0 U "
)
Fail2BanCIDRCount=$(
	grep -v '/' <<< "$Fail2BanCIDR" | grep -cve '^\s*$'
)

## Get Helix Hall Of Fame counts
HHoF_IPs=$(
	/sbin/route -n \
	| grep '\*' \
	| awk '{ print $1,$4,$5}' \
	| grep "UH" \
	| grep " 0"
)
HHoF_IPCount=$(
	grep -cve '^\s*$' <<< "$HHoF_IPs"
)
HHoF_CIDR=$(
	/sbin/route -n \
	| grep '\*' \
	| awk '{ print $1,$4,$5 }' \
	| grep " U " \
	| grep " 0"
)
HHoF_CIDRCount=$(
	grep -cve '^\s*$' <<< "$HHoF_CIDR"
)

## Get Whitelist counts
WhitelistedIPs=$(
	showwhitelist | grep -vE '^\s*$|^\s*#|127\.' | grep -v /
)
WhitelistedIPsCount=$(
	grep -cve '^\s*$' <<< "$WhitelistedIPs"
)
WhitelistedCIDR=$(
	showwhitelist | grep -vE '^\s*$|^\s*#|127\.' | grep /
)
WhitelistedCIDRCount=$(
	grep -cve '^\s*$' <<< "$WhitelistedCIDR"
)

## Set colors
export TERM=xterm-256color
ClrBlu=$(tput setaf 45)
ClrOff=$(tput sgr0)

color_range() {
	if [[ Count -eq 0 ]]; then
		ClrRng=82
	elif (( Count >= 1 && Count <= 100 )); then
		ClrRng=154
	elif (( Count >= 101 && Count <= 200 )); then
		ClrRng=184
	elif (( Count >= 201 && Count <= 300 )); then
		ClrRng=190
	elif (( Count >= 301 && Count <= 400 )); then
		ClrRng=226
	elif (( Count >= 401 && Count <= 500 )); then
		ClrRng=220
	elif (( Count >= 501 && Count <= 600 )); then
		ClrRng=214
	elif (( Count >= 601 && Count <= 700 )); then
		ClrRng=208
	elif (( Count >= 701 && Count <= 800 )); then
		ClrRng=202
	elif (( Count >= 801 && Count <= 900 )); then
		ClrRng=160
	elif (( Count >= 901 )); then
		ClrRng=196
	fi
}

insert_comma() {
	[[ Count -gt 999 ]] && Count=$(
		echo "$Count" | awk '{ printf "%\047d\n", $1 }'
	)
}

## Display Whitelist Counts
printf "\ncurrently whitelisted:\n"
Count=$WhitelistedIPsCount
insert_comma
printf "%-20s${ClrBlu}%-10s${ClrOff}" \
	"  Whitelisted IPs...:" " $Count" \

Count=$WhitelistedCIDRCount
insert_comma
printf "%-20s${ClrBlu}%-10s${ClrOff}\n" \
 	"Whitelisted CIDR...:" " $Count"

## Display Fail2Ban Counts
printf "\ncurrently banned:\n"
Count=$Fail2banIPCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Fail2Ban IPs......:" " $Count"

Count=$Fail2BanCIDRCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Fail2Ban CIDR......:" " $Count"

## Display Helix Hall of Fame Counts
Count=$HHoF_IPCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Hall of Fame IPs..:" " $Count"

Count=$HHoF_CIDRCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Hall of Fame CIDR..:" " $Count"