#!/bin/env bash

BanCounts=$(mktemp)
Whitelist=$(mktemp)

## Get ban counts
/opt/local/bin/showbancounts > "$BanCounts"
F2B_BannedIPCount=$(awk 'NR==5' "$BanCounts")
F2B_BannedCIDRCount=$(awk 'NR==8' "$BanCounts")
HHOF_IPCount=$(awk 'NR==20' "$BanCounts")
HHOF_CIDRCount=$(awk 'NR==23' "$BanCounts")
TotalIPCount=$(awk 'NR==35' "$BanCounts")
TotalCIDR_Count=$(awk 'NR==38' "$BanCounts")
ExpCIDR_Count=$(awk 'NR==41' "$BanCounts")
GrandTotalIP_Count=$(awk 'NR==44' "$BanCounts")

## Cleanup
rm -f "$BanCounts"

## Get Whitelist counts
showwhitelist | grep -vE '^\s*$|^\s*#|127\.' > "$Whitelist"

WhitelistedIPs=$(
	grep -v / "$Whitelist"
)
WhitelistedIPsCount=$(
	grep -cve '^\s*$' <<< "$WhitelistedIPs"
)
WhitelistedCIDR=$(
	grep / "$Whitelist"
)
WhitelistedCIDRCount=$(
	grep -cve '^\s*$' <<< "$WhitelistedCIDR"
)

## Cleanup
rm -f "$Whitelist"

## Set display colors
export TERM=xterm-256color
ClrBlu=$(tput setaf 45)
ClrOff=$(tput sgr0)

color_range() {
	if [[ Count -eq 0 ]]; then
		ClrRng=82
	elif (( Count >= 1 && Count <= 200 )); then
		ClrRng=154
	elif (( Count >= 201 && Count <= 400 )); then
		ClrRng=184
	elif (( Count >= 401 && Count <= 600 )); then
		ClrRng=190
	elif (( Count >= 601 && Count <= 800 )); then
		ClrRng=226
	elif (( Count >= 801 && Count <= 1000 )); then
		ClrRng=220
	elif (( Count >= 1001 && Count <= 2000 )); then
		ClrRng=214
	elif (( Count >= 2001 && Count <= 4000 )); then
		ClrRng=208
	elif (( Count >= 4001 && Count <= 8000 )); then
		ClrRng=202
	elif (( Count >= 8001 && Count <= 16000 )); then
		ClrRng=160
	elif (( Count >= 16001 )); then
		ClrRng=196
	fi
}

## Display a 'thousands' comma
insert_comma() {
	[[ Count -gt 999 ]] && Count=$(
		echo "$Count" | awk '{ printf "%\047d\n", $1 }'
	)
}

## Display Whitelist Counts
printf "\ncurrently whitelisted:\n"
printf "%-20s${ClrBlu}%-10s${ClrOff} %-20s${ClrBlu}%-10s${ClrOff}\n" \
	"  Whitelisted IPs...:" " ${WhitelistedIPsCount}" \
	"Whitelisted CIDR...:" " ${WhitelistedCIDRCount}"

## Display Fail2Ban Counts
printf "\ncurrently banned:\n"
Count=$F2B_BannedIPCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Fail2Ban IPs......:" " ${Count}"

Count=$F2B_BannedCIDRCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Fail2Ban CIDR......:" " ${Count}"

## Display Helix Hall of Fame Counts
Count=$HHOF_IPCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Hall of Fame IPs..:" " ${Count}"

Count=$HHOF_CIDRCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Hall of Fame CIDR..:" " ${Count}"

## Display more banned stats
printf "\nmore banned stats:\n"
Count=$TotalIPCount
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Total Single IPs..:" " ${Count}"

Count=$TotalCIDR_Count
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Total CIDR.........:" " ${Count}"

Count=$ExpCIDR_Count
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Expanded CIDR IPs.:" " ${Count}"

Count=$GrandTotalIP_Count
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Grand Total IPs....:" " ${Count}"
