#!/usr/bin/env bash

## Get Fail2Ban counts
F2B_IPS=$(/sbin/route -n | grep '\*' | awk '{ print $1,$4,$5 }' | grep -v " 0" | grep -v ".0 ")
F2B_IP_COUNT=$(grep -v '/' <<< "$F2B_IPS" | grep -cve '^\s*$')
F2B_CIDR=$(/sbin/route -n | grep '\*' | awk '{ print $1,$4,$5 }' | grep -v " 0" | grep ".0 U")
F2B_CIDR_COUNT=$(grep -v '/' <<< "$F2B_CIDR" | grep -cve '^\s*$')

## Get Helix Hall Of Fame counts
HHOF_IPS=$(/sbin/route -n | grep '\*' | awk '{ print $1,$4,$5}' | grep "UH")
HHOF_IP_COUNT=$(grep -cve '^\s*$' <<< "$HHOF_IPS")
HHOF_CIDR=$(/sbin/route -n | grep '\*' | awk '{ print $1,$4,$5 }' | grep " U " | grep " 0")
HHOF_CIDR_COUNT=$(grep -cve '^\s*$' <<< "$HHOF_CIDR")

## Get Whitelist counts
WHTLST_IPS=$(showwhitelist | grep -vE '^\s*$|^\s*#|127\.' | grep -v /)
WHTLST_IP_COUNT=$(grep -cve '^\s*$' <<< "$WHTLST_IPS")
WHTLST_CIDR=$(showwhitelist | grep -vE '^\s*$|^\s*#|127\.' | grep /)
WHTLST_CIDR_COUNT=$(grep -cve '^\s*$' <<< "$WHTLST_CIDR")

## Set colors
export TERM=xterm-256color
ClrBlu=$(tput setaf 45)
ClrOff=$(tput sgr0)

color_range() {
	if [[ Count -eq 0 ]]; then
		ClrRng=82
	elif (( Count >= 1 && Count <= 100 )); then
		ClrRng=154
	elif (( Count >= 101 && Count <= 200 )); then
		ClrRng=184
	elif (( Count >= 201 && Count <= 300 )); then
		ClrRng=190
	elif (( Count >= 301 && Count <= 400 )); then
		ClrRng=226
	elif (( Count >= 401 && Count <= 500 )); then
		ClrRng=220
	elif (( Count >= 501 && Count <= 600 )); then
		ClrRng=214
	elif (( Count >= 601 && Count <= 700 )); then
		ClrRng=208
	elif (( Count >= 701 && Count <= 800 )); then
		ClrRng=202
	elif (( Count >= 801 && Count <= 900 )); then
		ClrRng=160
	elif (( Count >= 901 )); then
		ClrRng=196
	fi
}

insert_comma() {
	[[ Count -gt 999 ]] && Count=$(
		echo "$Count" | awk '{ printf "%\047d\n", $1 }'
	)
}

## Display Whitelist Counts
printf "\ncurrently whitelisted:\n"
Count=$WHTLST_IP_COUNT
insert_comma
printf "%-20s${ClrBlu}%-10s${ClrOff}" \
	"  Whitelisted IPs...:" " $Count" \

Count=$WHTLST_CIDR_COUNT
insert_comma
printf "%-20s${ClrBlu}%-10s${ClrOff}\n" \
 	"Whitelisted CIDR...:" " $Count"

## Display Fail2Ban Counts
printf "\ncurrently banned:\n"
Count=$F2B_IP_COUNT
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Fail2Ban IPs......:" " $Count"

Count=$F2B_CIDR_COUNT
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Fail2Ban CIDR......:" " $Count"

## Display Helix Hall of Fame Counts
Count=$HHOF_IP_COUNT
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff} " \
	"  Hall of Fame IPs..:" " $Count"

Count=$HHOF_CIDR_COUNT
color_range
SetClrRange=$(tput setaf "$ClrRng")
insert_comma
printf "%-20s${SetClrRange}%-10s${ClrOff}\n" \
	"Hall of Fame CIDR..:" " $Count"