#!/usr/bin/env bash

Reboot=/var/run/reboot-required

if [[ -f $Reboot ]]; then
	if [[ -s $Reboot.pkgs ]]; then
		printf "%s\n" "ALERT: Recently installed upgrades require a reboot:"
		cat $Reboot.pkgs
	fi
fi
