#!/usr/bin/env bash

## Config
MaxUsage=90
BarWidth=50
# colors
ClrWht="\e[39m"
ClrGrn=$(tput setaf 46)
ClrRed=$(tput setaf 196)
ClrDim="\e[2m"
ClrOff="\e[0m"

## Disk usage: ignore ZFS, SquashFS & TmpFS
mapfile -t DFS < <(
	df -H -x zfs -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size \
	| sed '/\/home\//d' \
	| sed '/\/efi\//d' \
	| tail -n+2
)
printf "\ndisk usage:\n"

for Line in "${DFS[@]}"; do
    # get disk usage
    Usage=$(echo "$Line" | awk '{print $2}' | sed 's/%//')
    UsedWidth=$((($Usage*$BarWidth)/100))
    # color is ClrGrn if usage < MaxUsage, else ClrRed
    if [[ $usage -ge $MaxUsage ]]; then
        color=$ClrRed
    else
        color=$ClrGrn
    fi
    ## print green/red bar until used width
    Bar="[${color}"
    for ((i=0; i<$UsedWidth; i++)); do
        Bar+="="
    done
    # print dimmmed Bar until end
    Bar+="${ClrWht}${ClrDim}"
    for ((i=$UsedWidth; i<$BarWidth; i++)); do
        Bar+="="
    done
    Bar+="${ClrOff}]"
    # print usage Line & Bar
    echo "${Line}" | awk '{ printf("%-31s%+3s used out of %+4s\n", $1, $2, $3); }' | sed -e 's/^/  /'
    echo -e "${Bar}" | sed -e 's/^/  /'
done
