#!/bin/bash

## LVM Snapshots
NagiosCheck=/usr/local/src/rootsnap/check_rootsnap.sh

printf "%s\n" "rootsnap:"
if [[ -x $NagiosCheck ]]; then
	$NagiosCheck | sed 's/^/  /'
else
	/usr/local/sbin/rootsnap-latest | sed 's/^/  /'
fi
