#!/usr/bin/env bash

## LVM Snapshots
NagiosCheck=/usr/local/src/rootsnap/check_rootsnap.sh

printf "%s\n" "rootsnap:"
[[ -x $NagiosCheck ]] && $NagiosCheck | sed 's/^/  /'
/usr/local/sbin/rootsnap-latest | sed 's/^/  /'
