#!/usr/bin/env bash

## Use Nagios plugin to get a brief summary of apt updates
NagiosPath=/usr/local/nagios/libexec
if [[ -d $NagiosPath ]]; then
	printf '\n%s\n' \
		"Pending Package Updates:"
        ${NagiosPath}/check_apt \
	| cut -f1 -d"|" \
	| sed 's/^/  /'
fi
