#!/bin/bash

## Use Nagios plugin to get a brief summary of apt updates
NagPath=/usr/local/nagios/libexec
if [[ -d $NagPath ]]; then
	printf "\n%s\n" "Pending Package Updates:"
        $NagPath/check_apt \
	| cut -f1 -d"|" \
	| sed 's/^/  /'
fi
