#!/usr/bin/env bash

Reboot=$(pro system reboot-required 2>/dev/null)

if [[ $Reboot == yes ]]; then
	printf "\a\n%s\n" "Pending Kernel Update:"
	{ /usr/lib/update-notifier/update-motd-reboot-required
		pro system reboot-required 1>/dev/null
	} | sed 's/^/  /'
fi
