#!/usr/bin/env bash

Reboot=/var/run/reboot-required

if [[ -f $Reboot ]]; then
	if [[ -s ${Reboot}.pkgs ]]; then
		printf "\a\n%s\n" \
			"ALERT: Recently installed upgrades require a reboot:"
		sed -e 's/^/  /' ${Reboot}.pkgs
	fi
fi
