#!/bin/env bash

SYS_RB_RQ=$(pro system reboot-required 2>/dev/null)
if [[ ${SYS_RB_RQ} == yes ]]; then
	echo
	echo "Pending Kernel Update:"
	{
		/usr/lib/update-notifier/update-motd-reboot-required
		pro system reboot-required 1>/dev/null
	} | sed 's/^/  /'
fi
